---
output: github_document
bibliography: references.bib
nocite: |
  @bivand_applied_2013, @lovelace_geocomputation_inprogress, @muenchow_rqgis:_2017
---

# Geocomputation with R workshop - ERUM 2018
Geographic data is special and has become ubiquitous.
Hence, we need computational power, software and related tools to handle and extract the most interesting patterns of the ever-increasing amount of (geo-)data. 
This workshop gives an introduction how to do so using R.
It will introduce the audience how the two most important spatial data models - vector and raster - are implemented in R. 
The workshop will also give an introduction to spatial data visualization. 
Maps are a compelling way to display complex data in a beautiful way while allowing first inferences about spatial relationships and patterns.
Additionally, we will bridge R with Geographic Information Systems (GIS), i.e., we show how to combine the best of two worlds: the geoprocessing power of a GIS and the (geo-)statistical data science power of R.
We will do so with a use case presenting spatial and predictive modeling.

### Learning objectives
By the end of this workshop, the participants should:

* know how to handle the two spatial data models (vector and raster) in R.
* import/export different geographic data formats.
* know the importance of coordinate reference systems.
* be able to visualize geographic data in a compelling fashion.
* know about geospatial software interfaces and how they are integrated with R (GEOS, GDAL, QGIS, GRASS, SAGA).
* know about the specific challenges when modeling geographic data.

### Tutorial content

* The R spatial ecosystem
* Vector data model: simple features (**sf**)
* Raster data model (**raster**)
* Geographic data visualization (**ggplot2**, **mapview**, **tmap**)
* Bridges to GIS (**RQGIS**, **RSAGA**, **rgrass7**)
* Spatial modeling case study

### References



